version: '3.8'

services:
  duma-dashboard:
    build: .
    container_name: duma_mcdonalds
    restart: always
    ports:
      - "8005:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
